### ISSUE TITLE
Sketch Reports SketchIconsFramework.framework can't be verified

### ISSUE THREAD

**Issue by pjmdesi** [AMoreaux/Sketch-Icons#58]
Sketch error: **"SketchIconsFramework.framework" can't be verified because its integrity cannot be verified.**

**This software needs to be updated. Contact the developer for more information**

Sketch version: 57.1 (83088)
MacOS version: 10.15 Beta (19A536g)

Error occurs when trying to import icons **Plugins -> Sketch Icons -> Import Icons...**
It is a Mac software authentication error due to out of date software

Current fix is to find the dialogue under **Security & Privacy -> General** and click **Open Anyway**

![Screen Shot 2019-08-27 at 11 03 36 AM](https://user-images.githubusercontent.com/36543053/63787985-56f6d500-c8ba-11e9-8733-70532a3ede2e.png)

**Comment by itakesmallbytes** [comment]
Hey there @pjmdesi ,

I'm also running into this issue within macOS Catalina. I did exactly what you did however it still doesn't work. Have you found any other workaround?

@AMoreaux - What can we do to circumvent this issue? I saw in your documentation that Sketch Icons isn't compatible with El Capitan, however I'm running Catalina.

MacOS version: 10.15.2
Sketch version: 61.2

Thanks a bunch, appreciate it.
-Daisy

**Comment by pjmdesi** [comment]
Hi @itakesmallbytes,

I am not aware of another workaround. I actually stopped seeing this error a few macOS versions ago, so I'm not sure what can be done to fix this issue now.

**Comment by itakesmallbytes** [comment]
Thanks so much, appreciate it!

Sent from my iPhone

On Jan 13, 2020, at 11:16 AM, PJ <notifications@github.com> wrote:

﻿

Hi @itakesmallbytes <https://github.com/itakesmallbytes>,

I am not aware of another workaround. I actually stopped seeing this error
a few macOS versions ago, so I'm not sure what can be done to fix this
issue now.

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub
<https://github.com/AMoreaux/Sketch-Icons/issues/58?email_source=notifications&email_token=ANKXP2AJWCRGN4JQBXDAQDLQ5SHWXA5CNFSM4IQGIJC2YY3PNVWWK3TUL52HS4DFVREXG43VMVBW63LNMVXHJKTDN5WW2ZLOORPWSZGOEIZKD7Y#issuecomment-573743615>,
or unsubscribe

**Comment by Jennifervanvugt** [comment]
@pjmdesi Hello, I had this exact same problem yesterday. 

This is how I fixed it. 

Go to System Preference -> Security & Privacy -> General. 
Then unlock the lock.  

<img width="680" alt="Screenshot 2020-01-28 at 13 09 30" src="https://user-images.githubusercontent.com/60389492/73262842-737f9c00-41cf-11ea-9fda-6343f5753c26.png">

You will probably have an extra message here you need to confirm. "SketchIconsFramework.framework" and close your lock again.

**Comment by natarajgcb** [comment]
Still happening. Sketch version 73.1 (127209), macOS version 11.4, Sketch Icon version 5.0.1 (28 May 2020)... does Sketch-Icons not work with Sketch past version 52 as is listed in the `manifest.json`?
